[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-verifier = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
ciborium = { workspace = true }